server:
  port: 8080 #端口
spring:
  #修改zipkin使用rabbitmq采集数据
  zipkin:
    base-url: http://127.0.0.1:9411/  #server的请求地址
    sender:
      type: web #数据的传输方式 , 已http的形式向server端发送数据
  sleuth:
    sampler:
      probability: 1 #采样比
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  application:
    name: api-gateway-server #服务名称
  cloud: #配置SpringCloudGateway的路由
   gateway:
     routes:
     - id: product-service
       uri: http://127.0.0.1:9001
#       uri: lb://service-product
       predicates:
       - Path=/product/**  # 匹配路由条件
       filters:
#         - name: RequestRateLimiter
#           args:
#             # 使用SpEL从容器中获取对象
#             key-resolver: '#{@pathKeyResolver}'
#             # 令牌桶每秒填充平均速率
#             redis-rate-limiter.replenishRate: 1
#             # 令牌桶的上限
#             redis-rate-limiter.burstCapacity: 3
#         - RewritePath=/product-service/(?<segment>.*), /$\{segment}
#配置Eureka
eureka:
 client:
  service-url:
   defaultZone: http://localhost:9000/eureka/
 instance:
  prefer-ip-address: true #使用ip地址注册
  instance-id: ${spring.cloud.client.ip-address}:${server.port}
